### ISSUE TITLE
2+ different emails sent in same request merge their recipients

### ISSUE THREAD

**Issue by ryancramerdesign** [trk/WireMailPHPMailer#10]
@trk Following a form submission, I have a site where it sends an email to one group of people, and then sends a different email to another group. But the 2nd email ends up getting sent to the recipients of both the 1st and 2nd emails.  Somehow WireMailPhpMailer is not getting reset when new emails are started. 

I think the issue is likely [here](https://github.com/trk/WireMailPHPMailer/blob/master/WireMailPHPMailer.module.php#L59) in the `getModuleInfo` method where it has the `singular` property set as true. The `singular` property tells ProcessWire to only create one instance of the module in memory, which I think is the source of the issue. So whenever a new email is started via `wireMail()` or `$mail->new()`, etc., it's receiving the same instance of WireMailPhpMailer, which might already have recipients and/or other data already populated to it. I think it can be fixed just by changing `singular=false` and doing a modules > refresh.

**Comment by trk** [comment]
Thanks @ryancramerdesign
