### ISSUE TITLE
Module info 'autoload' property

### ISSUE THREAD

**Issue by ryancramerdesign** [trk/WireMailPHPMailer#2]
Hi @trk, thanks for writing this module. I was taking a closer look and see that you've got `'autoload' => true` in your getModuleInfo() method. That means ProcessWire is loading the module, and the module is creating an instance of PHPMailer, on every single request that ProcessWire serves. This is useful if you are attaching hooks into the core and such, but it doesn't look to me like the module is attaching any hooks or has any reason to be autoload? 

If you agree, would you consider changing the `autoload` setting to `false` in your getModuleInfo() method? I think it would make the module more efficient.  Thanks, —Ryan

**Comment by trk** [comment]
I lost my father, when i turn back to wrok i will check your requests.

19 Tem 2019 Cum 13:43 tarihinde Ryan Cramer <notifications@github.com> şunu
yazdı:

**Comment by ryancramerdesign** [comment]
Hi Iskender, I'm very sorry to hear about your father. I hope you are doing
alright.

The update I mentioned is of course very minor and just an idea for
whenever the next version is, someday. I also wanted to say you did really
nice work with this module. Thanks.
