### ISSUE TITLE
Multiple wireMail() calls reuse the same data

### ISSUE THREAD

**Issue by thetuningspoon** [trk/WireMailPHPMailer#6]
With the native WireMail it is possible to call wireMail() multiple times to send multiple emails. With WireMailPHPMailer, the data is retained between calls such that each subsequent email contains the prior recipients addresses as well as the new recipient, and the body still references the content of the prior email until you change it.

In other words:

```
$mail = wireMail();
$mail->subject('Test Subject');
$mail->body('Test Body');
$mail->to('example@example.com');
$mail->send();

$mail2 = wireMail();
$mail2->to('example2@example.com'); // This will go to both example and example2
// I don't even have to set subject and body since it is still set from above
$mail2->send();
```

This will result in the original email being sent again.

Also, setting body() without also setting bodyHTML() doesn't seem to work. No email gets sent.

**Comment by trk** [comment]
@thetuningspoon i updated module. Can you check this issue after apply update module on your side ?
