### ISSUE TITLE
Case typo? ($this->body vs $this->Body)

### ISSUE THREAD

**Issue by ryancramerdesign** [trk/WireMailPHPMailer#7]
I'm trying to assist someone that is having trouble getting WireMailPHPMailer to send HTML emails. I don't yet have file access to the installation to experiment with it it myself, but in trying to help them, I looked through the repo code and noticed something that looked like a potential error that might account for it, though uncertain. But wanted to report it just in case. 

Line 487 of WireMailPHPMailer.module.php has this:
~~~~~
if($this->body) {
  $this->AltBody($this->Body);
}
~~~~~
Notice that the if() statement refers to `$this->body` lowercase, while the AltBody() call refers to `$this->Body`, first letter uppercase. Since the if statement is matching something different than what it's using, I thought it might be a potential typo? If I get access to this install I'll experiment further to see if I can find out why he can't get it to send HTML emails.

**Comment by adrianbj** [comment]
> I don't yet have file access to the installation to experiment with it it myself

@ryancramerdesign - the is the perfect use case for Tracy's File Editor panel :)
