### ISSUE TITLE
HTML emails don't appear to work

### ISSUE THREAD

**Issue by ryancramerdesign** [trk/WireMailPHPMailer#8]
We're still trying to figure out how to get it to send HTML emails, which always come through as text emails. I think we spotted the issue:

- In PHPMailer the term setting `Body` refers to the HTML body and `AltBody` refers to text body. 
- In WireMail the setting `bodyHTML` refers to the HTML body and `body` refers to the text body. (Note the opposite meanings for WireMail `body` and PHPMailer `Body`).
- PHPMailer also has something called `msgHTML` which refers to HTML body with implied markup-to-text conversion (already handled natively by WireMail) and inlining of images (requiring a `$basedir`) and a function not implied by any WireMail method or setting. 

Given the above, I spotted a couple issues in the module that seem to prevent HTML+text emails from working: 

- The WireMailPHPMailer module has a `function Body(...)` which overrides the WireMail::body() function, because PHP functions are not case sensitive. In the WireMailPHPMailer module, it is setting the HTML body (i.e. PHPMailer `Body`), but in WireMail it refers to the text-only body. So they get mixed up.
- The WireMailPHPMailer::send() method sends the WireMail `bodyHTML` to PHPMailer’s `msgHTML`, which refers to HTML with conversions and inlines, something not implied by WireMail `bodyHTML`. 

The result is that we can't get the module to send an HTML+text message, as we end up with a text-only email with HTML stripped out. 

I was able to fix it by doing the following:

1. Remove the `function Body(...)` completely, as it's overriding the WireMail one with a different meaning (mixing up HTML with text-only). If you need to keep the method for some reason, it would need to populate `AltBody` (text-only) rather than `Body` (HTML). But then `WireMailPHPMailer::send()` would overwrite it again, as it uses WireMail's `$this->body`. It seems simplest just to remove the method since the base WireMail one already has the right behavior and enables it to work correctly. 

2. In the `send()` method at the bottom, replace this line:  
    ~~~~~
    $this->msgHTML($this->bodyHTML);
    ~~~~~
    with this:
    ~~~~~
    $this->options['Body'] = $this->bodyHTML;
    ~~~~~
    This is because `Body` in PHPMailer refers to the HTML body, while `msgHTML` refers to something different that is both redundant with WireMail (conversion) and doesn't translate directly to WireMail (inlining). 

Thanks and please let me know if I can provide any more info.

**Comment by trk** [comment]
Please let me know, fixes works or not ?

**Comment by ryancramerdesign** [comment]
@trk  Thanks for the update! It looks like it should fix it to me. I will ask the user that was having the issue to grab the latest copy and test it out.
